name: prolog_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  sizer: ^3.0.5
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  dio: ^5.8.0+1
  http_mock_adapter: ^0.6.1
  provider: ^6.1.5
  connectivity_plus: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0
  json_serializable: ^6.7.1
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/gestao_pneu/
    - assets/imgs/conexao/